on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '10.x'
        type: string
    secrets:
      PACKAGES_WRITE_PAT:
        description: The Access Token, which allows write of private packages
        required: true


jobs:
  bump-version:
    name: 'Bump Version on develop'
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}
    steps:
      - uses: 'actions/checkout@v3'   

      - name: 'cat package.json'
        run: cat ./package.json
      
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'cat package.json'
        run: cat ./package.json
      
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  publish:
    name: Publish NPM package to GH Packages
    runs-on: ubuntu-latest 
    needs: bump-version
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ needs.bump-version.outputs.new-version }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@medmera'
      
      - run: npm ci
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_WRITE_PAT }}
